/*CRIANDO BANCO DO EXERCICIO PROPOSTO*/

CREATE DATABASE LIVRARIA;

/*CRIANDO TABELA DO EXERCICIO PROPOSTO*/

CREATE TABLE LIVROS (
	LIVRO VARCHAR(30),
	AUTOR VARCHAR(30),
	SEXO CHAR(1),
	PAGINA INT(5),
	EDITORA VARCHAR(100),
	VALOR FLOAT(9,2),
	UF CHAR(2),
	ANO INT(4)
);

/*QUERY PARA TRAZER TODOS OS DADOS*/

SELECT * FROM LIVROS; /*EVITAR NO TRABALHO*/

/*QUERY PARA LIVRO E EDITORA*/

SELECT LIVRO, EDITORA FROM LIVROS;

/*QUERY PARA LIVRO E ESTATDO E AUTORES SEXO M*/

SELECT LIVRO, UF FROM LIVROS WHERE SEXO = 'M';
/*SELECT AUTOR, LIVRO, UF FROM LIVROS WHERE SEXO = 'M';*/

/*QUEREY PARA LIVRO E PAGINAS AUTORES SEXO F*/

SELECT LIVRO, PAGINA FROM LIVROS WHERE SEXO = 'F';
/*SELECT AUTOR, LIVRO, PAGINA FROM LIVROS WHERE SEXO = 'F';*/

/*QUEREY PARA VALORE E EDITORA DE SP */

SELECT LIVRO, EDITORA FROM LIVROS WHERE UF = 'SP';

/*QUEREY PARA AUTOR SEXO F UF SP OU RJ*/

SELECT AUTOR, SEXO FROM LIVROS WHERE SEXO = 'M' AND UF = 'SP' OR UF = 'RJ';

SELECT AUTOR, SEXO, UF FROM LIVROS WHERE SEXO = 'M' AND (UF = 'SP' OR UF = 'RJ');

/*POPULANDO BANCO*/

INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PAGINA, EDITORA, VALOR, UF, ANO) VALUES('CAVELEIRO REAL', 'ANA CLAUDIA', 'F', 465, 'ATLAS', '49.9', 'RJ', 2009);
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PAGINA, EDITORA, VALOR, UF, ANO) VALUES('SQL PARA LEIGOS', 'JOAO NUNES', 'M', 450, 'ADDISON', '98.00', 'SP', 2018);
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PAGINA, EDITORA, VALOR, UF, ANO) VALUES('RECEITAS CASEIRAS', 'CELIA TAVARES', 'F', 210, 'ATLAS', '45.0', 'RJ', 2008);
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PAGINA, EDITORA, VALOR, UF, ANO) VALUES('PESSOAS EFETIVAS', 'EDUARDO SANTOS', 'M', 390, 'BETA', '78.99', 'RJ', 2018);
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PAGINA, EDITORA, VALOR, UF, ANO) VALUES('HABITOS SAUDÁVEIS', 'EDUARDO SANTOS', 'M', 630, 'BETA', '150.98', 'RJ', 2019);
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PAGINA, EDITORA, VALOR, UF, ANO) VALUES('CASA MARROM', 'HERMES MACEDO', 'M', 250, 'BUBBA', '30.00', 'MG', 2016);
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PAGINA, EDITORA, VALOR, UF, ANO) VALUES('ESTACIO QUERIDO', 'GERALDP FRANCISCO', 'M', 310, 'INSIGNIA', '100.00', 'ES', 2015);
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PAGINA, EDITORA, VALOR, UF, ANO) VALUES('PRA SEMPRE AMIGAS', 'LEDA SILVA', 'F', 510, 'INSIGNA', '78.98', 'ES', 2011);
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PAGINA, EDITORA, VALOR, UF, ANO) VALUES('COPAS INESQUECIVEIS', 'MARCO ALCANTRA', 'M', 200, 'LARSON', '130.98', 'RS', 2018);
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PAGINA, EDITORA, VALOR, UF, ANO) VALUES('O PODER DA MENTE', 'CLARA MAFRA', 'F', 120, 'CONTINENTAL', '56.98', 'SP', 2017);

--------------------------------------------------------------------------------------------------------------------------------------------------------------------

/*EXERCICIO PROPOSTO*/

/*CONSIDERANDO O QUE VC APRENDEU SOBRE PERFORMANCE, RESOLVA OS EXERCIOCOS*/

SELECT COUNT(*) FROM FUNCIONARIOS;

--TRAGA OS FUNCIONARIOS QUE TRABALHAM NO DEPARTAMENTO DE FILMES OU NO DEPARTAMENTO DE ROUPAS

-- 21 FUNCIONARIOS - FILMES
-- 53 FUNCIONATIOS - ROUPAS

--COMO ESTAMOS TRABALHANDO COM OR E A SEGUNDA OPÇÃO E OPCIONAL 
--COLOCAMOS NA PRIMERA CONDIÇÃO QUEM TEM MAIS CHANCES DE UMA SAIDA
--VERDADEIRA, POIS A SEGUNDA CONDOÇAO NAO SERÁ CHECADA NESSE CASO

SELECT * FROM funcionarios
WHERE departamento = 'Roupas'	
OR
departamento = 'Filmes';

SELECT COUNT(*), departamento
FROM FUNCIONARIOS
GROUP BY departamento;

SELECT COUNT(*), departamento
FROM FUNCIONARIOS
GROUP BY departamento
ORDER BY 1;

WHERE DEPARTAMENTO = 'Filmes' OR DEPARTAMENTO = 'Roupas'

--O GESTOR DO MARKETING PEDIU A LISTA DAS FUNCIONARIAS QUE TRABALHEM NO DEPARTAMENTO DE FILMES OU NO DEPARTAMENTO LAR. ELE NECESSITA
--ENVIAR UM EMAIL PARA OS COLABORADORES DESSES DOIS SETORES. OR + AND *

-- 491 OCORRENCIAS

SELECT COUNT(*), sexo
FROM funcionarios
GROUP BY sexo;

--52 LAR
--21 FILMES

SELECT COUNT(*), departamento
FROM funcionarios
GROUP BY departamento;

SELECT * FROM FUNCIONARIOS 
WHERE
( DEPARTAMENTO = 'Lar' AND SEXO = 'Feminino')
OR
( DEPARTAMENTO = 'Filmes' AND SEXO = 'Feminino');

--TRAGA OS FUNCIONARIOS DO SEXO MASCULINO OU OS FUNCIONARIOS QUE TRABALHEM NO SETOR JARDIM

SELECT * FROM FUNCIONARIOS
WHERE
SEXO = 'Masculino' OR
DEPARTAMENTO = 'Jardim';